/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('@/layouts/Footer.vue')['default']
    CheckboxKonsumsi: typeof import('./src/components/checkbox/CheckboxKonsumsi.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectMenu: typeof import('./src/components/selection/SelectMenu.vue')['default']
    SelectRoom: typeof import('./src/components/selection/SelectRoom.vue')['default']
    SelectUnit: typeof import('./src/components/selection/SelectUnit.vue')['default']
  }
}
